---
- name: Create .kube directory for {{ kube_user }}
  file:
    path: "{{ kube_home }}/.kube"
    state: directory
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"

- name: Copy kube config to {{ kube_user }} home directory
  file:
    src: "{{ kube_user_config }}"
    dest: "{{ kube_home }}/.kube/config"
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    state: link