---
- name: Start etcd service
  systemd:
    state: started
    name: etcd
    daemon_reload: yes
    enabled: yes

- name: Confirm etcd healthy
  uri:
    body_format: "json"
    url: "{{ heath_check_url }}"
    validate_certs: yes
    return_content: yes
  register: etcd_response
  failed_when: "'true' not in etcd_response.content"