---
- name: Creating SSL directory
  file:
    path: "{{ etcd_config_dir }}/ssl"
    state: directory
    owner: root
    group: root
  when: (etcd.secured)

- name: Copying Root Certificate
  copy:
    src: "../files/etcd.ca.crt"
    dest: "{{ etcd_parameters.client_transport_security.trusted_ca_file }}"
    owner: root
    group: root
    mode: '0644'
  when: (etcd.secured)

- name: Copying Peer Certificate
  copy:
    src: "../files/etcd.cert.crt"
    dest: "{{ etcd_parameters.peer_transport_security.cert_file }}"
    owner: root
    group: root
    mode: '0644'
  when: (etcd.secured)

- name: Copying Peer Key
  copy:
    src: "../files/etcd.cert.key"
    dest: "{{ etcd_parameters.peer_transport_security.key_file }}"
    owner: root
    group: root
    mode: '0640'
  when: (etcd.secured)

- name: Copying Client Certificate
  copy:
    src: "../files/etcd.cert.crt"
    dest: "{{ etcd_parameters.client_transport_security.cert_file }}"
    owner: root
    group: root
    mode: '0644'
  when: (etcd.secured)

- name: Copying Client Key
  copy:
    src: "../files/etcd.cert.key"
    dest: "{{ etcd_parameters.client_transport_security.key_file }}"
    owner: root
    group: root
    mode: '0640'
  when: (etcd.secured)