apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  labels:
    app: kube-verify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-verify
spec:
  type: LoadBalancer
  loadBalancerIP: <SPECIFY_IP_ADDRESS>
  selector:
    app: kube-verify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web