apiVersion: v1
kind: Service
metadata:
  name: kube-verify
  annotations:
    metallb.universe.tf/address-pool: <SPECIFY_POOL_NAME>
spec:
  type: LoadBalancer
  selector:
    app: kube-verify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web