# defaults
cp_host: "{{ ansible_fqdn | default(ansible_eth0.ipv4.address) }}"
control_plane_port: "6443"
control_plane_endpoint: "https://{{cp_host}}:{{control_plane_port}}"
install_k3s: false

kube_user: "{{ ansible_user | default(root) }}"
kube_home: "{% if kube_user == 'root' %}/root{% else %}/home/{{kube_user}}{% endif %}"
kube_user_config: "{% if install_k3s == true %}/etc/rancher/k3s/k3s.yaml{% else %}/etc/kubernetes/admin.conf{% endif %}"

# k3s specific
k3s_bin_dir: "/usr/bin"
k3s_cri_arg: "{% if container_runtime == 'docker' %} --{{ container_runtime }}{% else %} --containerd{% endif %}"
k3s_server_coredns_enabled: "{{ k3s.server_components.coredns | default(false) }}"
k3s_server_servicelb_enabled: "{{ k3s.server_components.servicelb | default(false) }}"
k3s_server_traefik_enabled: "{{ k3s.server_components.traefik | default(false) }}"
k3s_server_local_storage_enabled: "{{ k3s.server_components.local_storage | default(false) }}"
k3s_server_metrics_server_enabled: "{{ k3s.server_components.metrics_server | default(false) }}"
k3s_service_type: "notify"
k3s_exec_args: "{{ 'server' | k3s_exec_arg_builder(k3s_cri_arg, apiserver_address, apiserver_port, advertise_address, advertise_port, tls_san, cluster_cidr, service_cidr, cluster_core_dns, cluster_domain, k3s_server_coredns_enabled, k3s_server_servicelb_enabled, k3s_server_traefik_enabled, k3s_server_local_storage_enabled, k3s_server_metrics_server_enabled) }}"
k3s_token_path: "/var/lib/rancher/k3s/server/node-token"
k3s_system_env: "/etc/systemd/system/k3s.env"

# kubernetes generic parameters
apiserver_address:
apiserver_port: 6443
advertise_address:
advertise_port:
tls_san:
cluster_cidr:
service_cidr:
cluster_core_dns:
cluster_domain:


# k8s/kubeadm specific
k8s_token_ttl: "1h"
k8s_token_description: "ansible-generated"