---
# Install OS common packages and configuration
- name: Prequisites
  tags: common
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: os.common
  
# Install Container Runtime
- name: Installing Container Runtime
  tags: cri
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: kubernetes.containerruntime
        
# Install etcd (when installing k3s)
- name: Installing ETCD
  tags: etcd
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: kubernetes.datastore
      when: (install_k3s is defined) and (install_k3s|bool == True)

# Install Kubernetes (k3s/k8s)
- name: Installing Kubernetes
  tags: kubernetes
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: kubernetes.common
    
# Configure Control Plane Node
- name: Configuring Control Plane Nodes
  hosts: controlplanes
  tasks:
    - import_role:
        name: kubernetes.controlplane

# Configurat Worker Nodes
- name: Configuring Worker Nodes
  hosts: workers
  tasks:
    - import_role:
        name: kubernetes.worker