---
# Install OS common packages and configuration
- name: Prequisites
  tags: common
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: os.common
  
# Install Container Runtime
- name: Installing Container Runtime
  tags: cri
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: kubernetes.containerruntime
  
# Install Kubernetes (k3s/k8s)
- name: Installing Kubernetes
  tags: kubernetes
  hosts: controlplanes:workers
  tasks:
    - import_role:
        name: kubernetes.common
    
# Configure Control Plane Node
- name: Configuring Control Plane Nodes
  hosts: controlplanes
  tasks:
    - import_role:
        name: kubernetes.controlplane

# Configurat Worker Nodes
- name: Configuring Worker Nodes
  hosts: workers
  tasks:
    - import_role:
        name: kubernetes.worker