---
- name: Check Kubernetes Version
  hosts: controlplanes:workers
  tasks:
  - name: Get Kubelet Minor Version
    shell: "if [ ! -z $(which kubelet) ]; then kubelet --version | awk '{ print $2 }' | grep -oP '([0-9].[0-9]+)'; fi"
    become: yes
    args:
      executable: "/bin/bash"
    register: kubelet_minor_version
    changed_when: false

  - name: Get Kubelet Revision
    shell: "if [ ! -z $(which kubelet) ]; then kubelet --version | awk '{ print $2 }' | grep -oP '(?!\\.)([0-9].[0-9]+)$'; fi"
    become: yes
    args:
      executable: "/bin/bash"
    register: kubelet_revision
    changed_when: false

  - debug:
      msg: "Kubelet Version: {{ kubelet_minor_version.stdout }}.{{ kubelet_revision.stdout }}"