---
- name: Download k3s Binary
  get_url: 
    url: "{{k3s_binary_download_url}}"
    dest: "{{k3s_bin_dir}}/k3s"
    mode: '0755'

- name: Create symlink for kubectl
  file:
    src: "{{k3s_bin_dir}}/k3s"
    dest: "/usr/bin/kubectl"
    owner: root
    group: root
    state: link

# really only useful for raspberry pi here
- name: Is this a Raspberry Pi?
  include_tasks: raspberrypi.yaml