---
- name: Add Kubernetes Apt Key
  apt_key:
    url: "{{ k8s_apt_key }}"
    keyring: "{{ k8s_keyring_path }}"
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Add Kubernetes Repository
  apt_repository:
    repo: "{{ k8s_apt_repo }}"
    state: present
  when:
    - ansible_os_family == "Debian"