# k8s
k8s_version: "1.20.1-00"
# ordering here is important as kubeadm will install kubelet and kubectl as dependencies
k8s_packages:
  - kubelet
  - kubectl
  - kubeadm

# k3s
k3s_github_url: "https://github.com/rancher/k3s/releases"
k3s_version: "v1.19.5+k3s1"
k3s_bin_dir: "/usr/bin"
k3s_suffix: "{% if ansible_architecture == 'arm64' or ansible_architecture == 'aarch64' %}-arm64{% endif %}"
k3s_binary_download_url: "{{k3s_github_url}}/download/{{k3s_version}}/k3s{{k3s_suffix}}"

# raspberry pi
cmdline_file: "{% if ansible_distribution == 'Ubuntu' %}/boot/firmware/cmdline.txt{% else %}/boot/cmdline.txt{% endif %}"
cmdline_arg: "cgroup_memory=1 cgroup_enable=memory"