---
- name: Add Docker Apt Key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when:
    - ansible_os_family == "Debian"
    
- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ distro }} stable"
    state: present
  when:
    - ansible_os_family == "Debian"