---
- name: Add Docker Apt Key
  apt_key:
    url: "{{ docker.apt_key }}"
    keyring: "{{ docker.keyring_path }}"
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker.apt_repo }}"
    state: present
  when:
    - ansible_os_family == "Debian"

