---
- name: Install OS Packages
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop: "{{apt_os_packages}}"
  when:
    - ansible_os_family == "Debian"

# set os timezone
- name: Set Timezone
  timezone:
    name: "{{vm_timezone}}"

# Disable swap
- name: Removing swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0
