---
- name: Install OS Packages
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop: "{{apt_os_packages}}"
  when:
    - ansible_os_family == "Debian"

# set os timezone
- name: Set Timezone
  timezone:
    name: "{{vm_timezone}}"

# Disable swap
- name: Removing swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Enable overlay
  modprobe:
    name: overlay
    state: present
    persistent: present

- name: Enable br_netfilter
  modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Set net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Set net.bridge.bridge-nf-call-iptables=1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Set net.bridge.bridge-nf-call-ip6tables=1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes

- name: Set fs.inotify.max_user_watches=1048576
  sysctl:
    name: fs.inotify.max_user_watches
    value: '1048576'
    state: present
    reload: yes

- name: Set fs.inotify.max_user_instances=8192
  sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    state: present
    reload: yes

- name: Set vm.max_map_count=524288
  sysctl:
    name: vm.max_map_count
    value: '524288'
    state: present
    reload: yes