---
- name: Applying Node Labels
  shell: "kubectl --kubeconfig {{ kube_user_config }} label node {{ ansible_fqdn }} node-role.kubernetes.io/{{ item }}"
  become: no
  args:
    executable: "/bin/bash"
  delegate_to: "{{ groups['bootstrap'][0] }}"
  delegate_facts: true
  with_items: "{{ combined_node_labels }}"
