---
- set_fact:
    join_token: "{{ hostvars['dummy_join']['join_token'] }}"
    join_ca_cert_hash: "{{ hostvars['dummy_join']['join_ca_cert_hash'] }}"
    join_certificate_key: "{{ hostvars['dummy_join']['join_certificate_key'] }}"
  run_once: true

# - debug:
#     msg:
#       - "join_token: {{ join_token }}"
#       - "ca_cert_hash: {{ join_ca_cert_hash }}"
#       - "certificate-key: {{ join_certificate_key }}"

- name: Start kubelet service
  systemd:
    name: kubelet
    state: started
  register: kubelet_status

- name: Check for existing kubelet.conf
  stat:
    path: "{{ kubelet_config_path }}"
  register: kubelet_config_check

- name: Copy kubeadm join configuration file to host
  template:
    src: "../templates/{{ kube_join_config_name }}.j2"
    dest: "{{ kube_join_config_path }}"
  when: "(kubelet_config_check.stat.exists == false)"

- name: Running join command
  shell: "kubeadm join --config {{ kube_join_config_path }}"
  become: yes
  args:
    executable: "/bin/bash"
  register: kubeadm_join_output
  when: "(kubelet_config_check.stat.exists == false)"

- debug:
    msg: "{{ kubeadm_join_output.stdout }}"
  when: "(kubelet_config_check.stat.exists == false)"